#ifndef _PORTS_H_
#define _PORTS_H_

#include <stm32f4xx.h>

// ---> NUCLEO BOARD LED PORTS <---

#define LED_NUC_PORT GPIOB

#define LED_GREEN_NUC  0
#define LED_BLUE_NUC   7
#define LED_RED_NUC   14

#define NUC_LEDS_INIT_DEC()    LED_NUC_PORT->MODER |=  (1u << (LED_GREEN_NUC*2))|(1u << (LED_BLUE_NUC*2))|(1u << (LED_RED_NUC*2))
#define NUC_LEDS_INIT_PROOF()  LED_NUC_PORT->MODER &= ~((2u << (LED_GREEN_NUC*2))|(2u << (LED_BLUE_NUC*2))|(2u << (LED_RED_NUC*2)))

// ---> EXTERNAL PUSH/PULL LED PORTS <---

#define LED_EXT_PP_PORT GPIOC

#define LED_RED_PP_EXT     2
#define LED_YELLOW_PP_EXT  3
#define LED_GREEN_PP_EXT   6

#define EXT_LEDS_INIT_PP() LED_EXT_PP_PORT->OTYPER |= (0 << LED_RED_PP_EXT)|(0 << LED_YELLOW_PP_EXT)|(0 << LED_GREEN_PP_EXT) 

#define EXT_LEDS_INIT_PP_RED_DEC() LED_EXT_PP_PORT->MODER |= (1u << (LED_RED_PP_EXT*2))
#define EXT_LEDS_INIT_PP_RED_PROOF() LED_EXT_PP_PORT->MODER &= ~(2u << (LED_RED_PP_EXT*2))

#define EXT_LEDS_INIT_PP_YELLOW_DEC() LED_EXT_PP_PORT->MODER |= (1u << (LED_YELLOW_PP_EXT*2))
#define EXT_LEDS_INIT_PP_YELLOW_PROOF() LED_EXT_PP_PORT->MODER &= ~(2u << (LED_YELLOW_PP_EXT*2))

#define EXT_LEDS_INIT_PP_GREEN_DEC() LED_EXT_PP_PORT->MODER |= (1u << (LED_GREEN_PP_EXT*2))
#define EXT_LEDS_INIT_PP_GREEN_PROOF() LED_EXT_PP_PORT->MODER &= ~(2u << (LED_GREEN_PP_EXT*2))

// ---> EXTERNAL OPEN DRAIN LED PORTS <--- 

#define LED_EXT_OD_PORT_A GPIOF
#define LED_EXT_OD_PORT_B GPIOC

#define LED_WHITE_OD_EXT  10
#define LED_RED_OD_EXT    7
#define LED_YELLOW_OD_EXT 8
#define LED_GREEN_OD_EXT  9

#define EXT_LEDS_INIT_OD_PORTF() LED_EXT_OD_PORT_A->OTYPER |= (1 << LED_WHITE_OD_EXT)

#define EXT_LEDS_INIT_OD_DEC_WHITE_PORTF()   LED_EXT_OD_PORT_A->MODER |=  (1u << (LED_WHITE_OD_EXT*2))
#define EXT_LEDS_INIT_OD_PROOF_WHITE_PORTF() LED_EXT_OD_PORT_A->MODER &= ~(2u << (LED_WHITE_OD_EXT*2))

#define EXT_LEDS_INIT_OD_PORTC() LED_EXT_OD_PORT_B->OTYPER |= (1 << (LED_RED_OD_EXT))|(1 << (LED_YELLOW_OD_EXT))|(1 << (LED_GREEN_OD_EXT))

#define EXT_LEDS_INIT_OD_DEC_RED_PORTC()      LED_EXT_OD_PORT_B->MODER |=  (1u << (LED_RED_OD_EXT*2))
#define EXT_LEDS_INIT_OD_PROOF_RED_PORTC()    LED_EXT_OD_PORT_B->MODER &= ~(2u << (LED_RED_OD_EXT*2))

#define EXT_LEDS_INIT_OD_DEC_YELLOW_PORTC()   LED_EXT_OD_PORT_B->MODER |=  (1u << (LED_YELLOW_OD_EXT*2))
#define EXT_LEDS_INIT_OD_PROOF_YELLOW_PORTC() LED_EXT_OD_PORT_B->MODER &= ~(2u << (LED_YELLOW_OD_EXT*2))

#define EXT_LEDS_INIT_OD_DEC_GREEN_PORTC()    LED_EXT_OD_PORT_B->MODER |=  (1u << (LED_GREEN_OD_EXT*2))
#define EXT_LEDS_INIT_OD_PROOF_GREEN_PORTC()  LED_EXT_OD_PORT_B->MODER &= ~(2u << (LED_GREEN_OD_EXT*2))

// ---> EXTERNAL USART PORTS <---

#define USART_MODULE USART3
#define USART_PORT   GPIOC
#define USART_TX_PIN 10
#define USART_RX_PIN 11
#define BAUDRATE     9600


// ---> LCD PUSH/PULL FUNCTIONS <---
#define SET_LCD_BKL() LCD_PORT->BSRR =  (1 << (LCD_BKL_PIN+16))
#define CLR_LCD_BKL() LCD_PORT->BSRR = ~(1 << (LCD_BKL_PIN+16))

// ---> NUCLEO BOARD LED FUNCTIONS <---

#define INIT_CLK_NUC_B() RCC->AHB1ENR |= RCC_AHB1ENR_GPIOBEN

#define SET_NUC_LED_GREEN() LED_NUC_PORT->BSRR =  (1 << (LED_GREEN_NUC+16))
#define CLR_NUC_LED_GREEN() LED_NUC_PORT->BSRR = ~(1 << (LED_GREEN_NUC+16))

#define SET_NUC_LED_BLUE()  LED_NUC_PORT->BSRR =  (1 << (LED_BLUE_NUC+16))
#define CLR_NUC_LED_BLUE()  LED_NUC_PORT->BSRR = ~(1 << (LED_BLUE_NUC+16))  

#define SET_NUC_LED_RED()   LED_NUC_PORT->BSRR =  (1 << (LED_RED_NUC+16))
#define CLR_NUC_LED_RED()   LED_NUC_PORT->BSRR = ~(1 << (LED_RED_NUC+16))

#define SET_NUC_TOGGLE_LED_GREEN() LED_NUC_PORT->ODR ^= (1 << LED_GREEN_NUC)
#define SET_NUC_TOGGLE_LED_BLUE()  LED_NUC_PORT->ODR ^= (1 << LED_BLUE_NUC)
#define SET_NUC_TOGGLE_LED_RED()   LED_NUC_PORT->ODR ^= (1 << LED_RED_NUC)  

// ---> EXTERNAL PUSH/PULL LED FUNCTIONS <---

#define INIT_CLK_PP_C() RCC->AHB1ENR |= RCC_AHB1ENR_GPIOCEN 

#define SET_EXT_LED_PP_RED()    LED_EXT_PP_PORT->BSRR =  (1 << (LED_RED_PP_EXT+16))
#define CLR_EXT_LED_PP_RED()    LED_EXT_PP_PORT->BSRR = ~(1 << (LED_RED_PP_EXT+16))

#define SET_EXT_LED_PP_YELLOW() LED_EXT_PP_PORT->BSRR =  (1 << (LED_YELLOW_PP_EXT+16))
#define CLR_EXT_LED_PP_YELLOW() LED_EXT_PP_PORT->BSRR = ~(1 << (LED_YELLOW_PP_EXT+16))

#define SET_EXT_LED_PP_GREEN()  LED_EXT_PP_PORT->BSRR =  (1 << (LED_GREEN_PP_EXT+16))
#define CLR_EXT_LED_PP_GREEN()  LED_EXT_PP_PORT->BSRR = ~(1 << (LED_GREEN_PP_EXT+16))

#define SET_EXT_TOGGLE_PP_RED() LED_EXT_PP_PORT->ODR ^= (1 << LED_RED_PP_EXT)
#define SET_EXT_TOGGLE_PP_YELLOW() LED_EXT_PP_PORT->ODR ^= (1 << LED_YELLOW_PP_EXT)
#define SET_EXT_TOGGLE_PP_GREEN() LED_EXT_PP_PORT->ODR ^= (1 << LED_GREEN_PP_EXT)

// ---> EXTERNAL OPEN DRAIN LED FUNCTIONS <---

#define INIT_CLK_OD_F() RCC->AHB1ENR |= RCC_AHB1ENR_GPIOFEN
#define INIT_CLK_OD_C() RCC->AHB1ENR |= RCC_AHB1ENR_GPIOCEN

#define SET_EXT_LED_OD_WHITE()  LED_EXT_OD_PORT_A->BSRR =  (1 << (LED_WHITE_OD_EXT+16))
#define CLR_EXT_LED_OD_WHITE()  LED_EXT_OD_PORT_A->BSRR = ~(1 << (LED_WHITE_OD_EXT+16))

#define SET_EXT_LED_OD_RED()    LED_EXT_OD_PORT_B->BSRR =  (1 << (LED_RED_OD_EXT+16))
#define CLR_EXT_LED_OD_RED()    LED_EXT_OD_PORT_B->BSRR = ~(1 << (LED_RED_OD_EXT+16))

#define SET_EXT_LED_OD_YELLOW() LED_EXT_OD_PORT_B->BSRR =  (1 << (LED_YELLOW_OD_EXT+16))
#define CLR_EXT_LED_OD_YELLOW() LED_EXT_OD_PORT_B->BSRR = ~(1 << (LED_YELLOW_OD_EXT+16))

#define SET_EXT_LED_OD_GREEN()  LED_EXT_OD_PORT_B->BSRR =  (1 << (LED_GREEN_OD_EXT+16))
#define CLR_EXT_LED_OD_GREEN()  LED_EXT_OD_PORT_B->BSRR = ~(1 << (LED_GREEN_OD_EXT+16))

#define SET_EXT_TOGGLE_OD_WHITE() LED_EXT_OD_PORT_A->ODR ^= (1 << LED_WHITE_OD_EXT)

#define SET_EXT_TOGGLE_OD_RED() LED_EXT_OD_PORT_B->ODR ^= (1 << LED_RED_OD_EXT)
#define SET_EXT_TOGGLE_OD_YELLOW() LED_EXT_OD_PORT_B->ODR ^= (1 << LED_YELLOW_OD_EXT)
#define SET_EXT_TOGGLE_OD_GREEN() LED_EXT_OD_PORT_B->ODR ^= (1 << LED_GREEN_OD_EXT)

#endif


